---
title: "Введение в Linux, `lexd`, `git` и `make`"
author: "G. Moroz"
date: "2 декабря 2021"
output: 
  html_document:
    toc: true
    toc_position: right
    toc_depth: 2
    toc_float: yes
    number_sections: true
---

```{r setup, include=FALSE}
library('knitr')
knit_hooks$set(prompt = function(before, options, envir) {options(prompt = "$ ")})
opts_chunk$set(comment = "", prompt = TRUE)
```

Название этих материалов может выглядеть немного слишком амбициозным, однако, надеюсь все понимают, что все, что перечислено в заглавии является отдельной большой сложной темой, знание в которой вы можете (скорее всего даже вам придется) углубить самостоятельно.

В этих материалах я исхожу из предположения, что вы уже поставили что-то linux-образное, умеете  создавать, читать и удалять файлы, а также знакомы с элементарными командами:

* `ls`
* `cd`
* `pwd`
* `mkdir`
* `touch`
* `cat`
* `rm`
* `nano`
* и другие

# Введение в консольные программы на Linux[^1]

## `bash`

[^1]: Вообще-то многое, что я буду говорить лучше бы было описывать как свойство `Unix`, но я позволил себе пренебречь жаргоном.

Когда вы открываете линуксовскую командную строку, чаще всего вы сталкиваетесь с интерпретатором `bash` -- это такая командная оболочка, которая позволяет отдавать команды вашей операционной системе и компьютеру.

```{bash}
echo "hi all"
```

Разумеется, когда дело доходит до больших и сложных программ, то их записывают в скрипты, которым обычно дают расширение `.sh` и начинают с [шебанга](https://en.wikipedia.org/wiki/Shebang_(Unix)). Вот пример простой программы:

```my_program.sh
#!/bin/bash

echo "Please enter your name: "
read name
echo "Nice to meet you $name"
```

Если вы запишите эту программу в файл `my_script.sh`, то ее потом можно вызвать следующей командой

```{bash, eval = FALSE}
sh my_script.sh
```

В интернете много ресурсов для изучения `bash`, но вам не придется писать на нем программ (но придется запускать), так что посвящать время его дальнейшому изучению -- дело исключительно добровольное.

## Консольные программы

Для `bash` написано очень много самых разных программ. Важно понимать, что их все (естественно, после установки, если это необходимо) можно вызвать набрав в консоли название программы. Очень важно понимать, что у большинства программ есть какие-то аргументы (почему-то их принято называть флагами), которые перечисляют после минуса.

```{bash}
ls
```

```{bash}
ls -l
```

Флагов может быть больше одного:

```{bash}
ls -l -a -h
```

Флаги можно смешать:

```{bash}
ls -lah
```

Флаги можно еще смешать:
```{bash}
ls -hla
```

Флаги различаются по длинне. Однобуквенные флаги можно перечислить вместе после минуса. Однако бывают длинные флаги, и для того, чтобы отличить их от комбинации коротких флагов, ставят два минуса:

```{bash}
ls --all
```

```{bash}
ls -a
```

Чтобы узнать какие у программы есть флаги, чаще всего можно либо добавить флаг `--help`, либо использовать программу `man`. Еще есть полезная программа `tldr`, которая дает краткое саммари и примеры, однако она требует установки.

[//]: # (ГМ: почему-то `tldr` добавляет время, когда исполняется внутри Rmd...)

```{bash, eval = FALSE}
tldr ls
```

```
ls
List directory contents.

 - List files one per line:
   ls -1

 - List all files, including hidden files:
   ls -a

 - List all files, with trailing / added to directory names:
   ls -F

 - Long format list (permissions, ownership, size and modification date) of all files:
   ls -la

 - Long format list with size displayed using human readable units (KB, MB, GB):
   ls -lh

 - Long format list sorted by size (descending):
   ls -lS

 - Long format list of all files, sorted by modification date (oldest first):
   ls -ltr
```

При этом `python` или `R` интерпретаторы --- это такие же программы.

```{bash}
python -c "print unichr(234)"
```

```{bash}
R --silent -e "Sys.Date()"
```

# Введение в `lexd`

[`lexd`](https://github.com/apertium/lexd) --- это программа для описания морфонологии языка, разработанная в [apertium](https://apertium.org) (для этой цели также используют программы [`lexc` и `lttoolbox`](https://wiki.apertium.org/wiki/Lttoolbox_and_lexc)).

## Установка

Программу можно установить следующим образом:

```{bash, eval = FALSE}
wget https://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash
sudo apt-get install lexd
```

## Пример использования

Давайте попробуем смоделировать следующие данные:

| cyryllic      | IPA            | gloss                  |
|---------------|----------------|------------------------|
| берка         | berka          | змея-ABS               |
| берку-ди      | berku-di       | змея.OBL-ERG           |
| берку-хъи     | berku-qχi      | змея.OBL-INSTR         |
| берку-лIи     | berku-tɬ’i     | змея.OBL-SUB-ESSIVE    |
| берку-лIи     | berku-tɬ’i     | змея.OBL-SUB-LATIVE    |
| берку-лIи-кку | berku-tɬ’i-kːu | змея.OBL-SUB-ELATIVE   |
| берку-ъа      | berku-ʔa       | змея.OBL-SUPER-ESSIVE  |
| берку-ъо      | berku-ʔo       | змея.OBL-SUPER-LATIVE  |
| берку-ъа-кку  | berku-ʔa-kːu   | змея.OBL-SUPER-ELATIVE |


# Введение в `git`

# Введение в `make`